name: Malayah App CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  android-ci:
    name: Android CI/CD Pipeline
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up JDK (Java 17)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 35
          build-tools: '35.0.0'
          target: 'android-35'

      # 4. Grant execute permissions to Gradle wrapper
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      # 5. Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 6. Debug: Verify Gradle and Kotlin versions
      - name: Verify Gradle and Kotlin setup
        run: |
          ./gradlew --version
          java -version

      # 7. Build Debug APK with detailed logging
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace --info

      # 8. Run Android Lint
      - name: Run Android Lint
        run: ./gradlew lintDebug --stacktrace

      # 9. Run Instrumentation Tests
      - name: Run Instrumentation Tests
        run: ./gradlew connectedDebugAndroidTest --stacktrace

      # 10. Upload Debug APK
      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
